[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httptools>=0.6.4",
    "starlette>=0.46.2",
    "uvicorn>=0.34.1",
]
