name: Test Suite

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Run Tests
        run: |
          pipx install poetry
          poetry install
          poetry run pytest
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install Node.js and Lint Frontend
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
          \. "$HOME/.nvm/nvm.sh"
          nvm install 22
          pushd frontend
          npm install
          npm run lint
          popd

      - name: Install Poetry and Lint Python
        run: |
          pipx install poetry
          poetry install
          poetry run ruff check .
          poetry run ruff format --check .
